server:
  port: 9090

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/project1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update # update setting means allow hibernate to create/modify tables by itself and no need to create table explicitly
    show-sql: true
  h2:
    console:
      enabled: true

  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000 # 60 seconds = 1min so every min cache would be cleared

  kafka: # link: http://localhost:8080/ui/clusters/local/all-topics/meeting_notifications/messages?keySerde=String&valueSerde=String&limit=100
    bootstrap-servers: localhost:9094






